
["TnT Mallet Settings"]
	#Range: 1 ~ 10000
	"Mallet Durability" = 300
	"Explosions Start Fires" = true
	"Targets Explodes in Melee" = true
	"Explosive Strikes Break Blocks" = false
	"Generate Absorb Shield before Explosion" = true

["Explosive Orb Settings"]
	"Explosions Start Fires" = false
	"Targets Explodes in Melee" = true
	#Range: 1 ~ 10000
	"Orb Durability" = 10
	"Generate Absorb on Melee" = true

["Molotov Settings"]
	"Molotov Breaks in Melee" = true
	#Range: 1 ~ 10000
	"Molotov Durability" = 3

